DEGRADE_LIST = [
    "Eat my ass",
    "you're about as important as a white crayon",
    "If you think Crime is gonna get you out of this, you're dumber than you look",
    "This ass is not going to eat itself",
    "You're so shit, you should uninstall",
    "Don’t talk to me. You don’t deserve to talk to me.",
    "I want you to go on your knees",
    "Let me give you some Mommy Issues",
    "If laughter is the best medicine, your face must be curing the world.",
    "I'd agree with you, but then we'd both be wrong.",
    "You must have a very colorful life, considering how often you shade people.",
    "It's a shame you can't Photoshop your personality.",
    "If I had a face like yours, I'd sue my parents.",
    "Are you always so stupid, or is today a special occasion?",
    "If you were any slower, you'd be going backward.",
    "Is your name 'Google'? Because you have everything I've been searching for.",
    "You're so ugly, even a blind man wouldn't date you.",
    "Mirrors can't talk. Lucky for you, they can't laugh either.",
    "You bring everyone so much joy... when you leave the room.",
    "You're not stupid; you just have bad luck thinking.",
    "It's impossible to underestimate you.",
    "I'd call you a tool, but even they serve a purpose.",
    "You're like a ray of sunshine on a really cloudy day.",
    "You're so dense, light bends around you.",
    "I used to think you were a pain in the neck. Now I have a much lower opinion of you.",
    "You're not the dumbest person on Earth, but you sure better hope they don't die.",
    "You're not stupid; you just have bad luck thinking.",
    "I would agree with you but then we'd both be wrong.",
    "You're not pretty enough to have such an ugly personality.",
    "Are you always this obnoxious, or is today a special occasion?",
    "I'd explain it to you, but I don't have any crayons.",
    "I'm not saying you're dumb; you just have bad luck thinking.",
    "You're not as bad as people say. You're worse.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "You have a face that makes onions cry.",
    "Don't worry, you're not as dumb as you look.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'd agree with you, but then we'd both be wrong.",
    "If you were any slower, you'd be going backward.",
    "I'm not insulting you; I'm describing you.",
    "I'm not saying you're stupid, but you have bad luck thinking.",
    "You're not a complete idiot. Some parts are missing.",
    "You must have been dropped on your head as a child, but it's not too late to improve.",
    "You're not the sharpest tool in the shed, but you are a tool.",
    "Some cause happiness wherever they go; you, whenever you go.",
    "You're the reason they put instructions on shampoo bottles.",
    "Don't worry; you're not the first person to disappoint me.",
    "You're like a human version of period cramps.",
    "You bring everyone so much joy when you leave the room.",
    "I'm not saying you're ugly, but you have a face only a mother could love.",
    "If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
    "You're proof that evolution can go in reverse.",
    "I'd call you a tool, but even they have some usefulness.",
    "You have the personality of a wet weekend.",
    "You're the human version of period cramps.",
    "You're not stupid; you just have bad luck thinking.",
    "Is your name 'Wi-Fi'? Because I'm really feeling a connection.",
    "I don't have the time or crayons to explain this to you.",
    "I'd agree with you, but then we'd both be wrong.",
    "I'm not insulting you; I'm describing you.",
    "You're the reason they put 'do not insert into ear' on Q-tips.",
    "You must have been dropped on your head as a child, but it's not too late to improve.",
    "You're like a human version of a headache.",
    "I'm not saying you're dumb, but you have bad luck thinking.",
    "You're the reason the gene pool needs a lifeguard.",
    "If you were any less intelligent, you'd be a rock.",
    "You're not stupid; you just have bad luck thinking.",
    "I'd call you a genius, but I'm not sure it would be accurate.",
    "You're not a complete idiot. Some parts are missing.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "If ignorance is bliss, you must be the happiest person alive.",
    "I would agree with you but then we'd both be wrong.",
    "You're like a human version of nails on a chalkboard.",
    "You're not the sharpest tool in the shed, but you are a tool.",
    "You have an entire life to be an idiot. Why not take today off?",
    "You're like a human version of nails on a chalkboard.",
    "I'm not saying you're ugly, but you could scare a buzzard off a gut wagon.",
    "You're the reason they put instructions on shampoo bottles.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "I'm not insulting you; I'm describing you.",
    "You have a face that makes onions cry.",
    "If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
    "You're proof that evolution can go in reverse.",
    "I'd call you a tool, but even they have some usefulness.",
    "You're not the sharpest tool in the shed, but you are a tool.",
    "Some cause happiness wherever they go; you, whenever you go.",
    "Don't worry; you're not the first person to disappoint me.",
    "You're like a human version of period cramps.",
    "You bring everyone so much joy when you leave the room.",
    "I'm not saying you're ugly, but you have a face only a mother could love.",
    "If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You have the personality of a wet weekend.",
    "You're the human version of period cramps.",
    "You're not stupid; you just have bad luck thinking.",
    "Some cause happiness wherever they go; you, whenever you go.",
    "You're the reason they put instructions on shampoo bottles.",
    "Don't worry; you're not the first person to disappoint me.",
    "You're like a human version of period cramps.",
    "You bring everyone so much joy when you leave the room.",
    "I'm not saying you're ugly, but you have a face only a mother could love.",
    "If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You have the personality of a wet weekend.",
    "You're the human version of period cramps.",
    "You're not stupid; you just have bad luck thinking.",
    "I don't have the time or crayons to explain this to you.",
    "I'd agree with you, but then we'd both be wrong."
]

FLIRTS_LIST = [
    "The only movie I want to watch is the one we both make at home",
    "You're the only mistake I want to make tonight",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Do you have a map? I keep getting lost in your eyes.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a name or can I call you mine?",
    "Is your smile made of magnets? Whenever I look at you, you attract me.",
    "Are you made of copper and tellurium? Because you're Cu-Te.",
    "I must be a snowflake because I've fallen for you.",
    "I'm not a photographer, but I can definitely picture us together.",
    "You're so sweet, you must be a confectionery angel.",
    "Your smile could light up the darkest of rooms.",
    "I must be a snowflake because I've fallen for you all over again.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "I'd say God bless you, but it looks like he already did.",
    "Are you an angel? Because heaven is missing one.",
    "Can I follow you home? Cause my parents always told me to follow my dreams.",
    "You must be a campfire because you're hot and I want s'more.",
    "Do you have a name, or can I call you mine?",
    "Are you a time traveler? Because I can see you in my future.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "You're so stunning that you must be the reason for global warming.",
    "Can I take a picture with you to prove to my friends that angels exist?",
    "Your hand looks heavy. Can I hold it for you?",
    "Do you believe in love at first sight, or should I walk by again?",
    "Is your name Google? Because you have everything I've been searching for.",
    "You must be a magician because whenever I look at you, everyone else disappears.",
    "Is your name Wi-Fi? Because I'm really feeling a connection.",
    "Are you a campfire? Because you're hot and I want s'more.",
    "Your smile must be a black hole because it's irresistibly pulling me in.",
    "Is your dad a baker? Because you're a cutie pie!",
    "You must be a treasure because I'm digging the way you sparkle.",
    "If you were a cat, you'd purr-fect.",
    "I must be a snowflake because I've fallen for you.",
    "If you were a fruit, you'd be a fine-apple.",
    "Is your name Chapstick? Because you're da balm!",
    "Do you have a name, or can I call you mine?",
    "Can you lend me a kiss? I promise I'll give it back.",
    "Is your name Cinderella? Because I see that dress disappearing by midnight.",
    "You must be a bank loan because you have my interest.",
    "Are you a camera? Every time I look at you, I smile.",
    "Do you have a Band-Aid? I just scraped my knee falling for you.",
    "If beauty were a crime, you'd be serving a life sentence.",
    "Your eyes are as blue as the ocean, and I'm lost at sea.",
    "Is your name Angel? Because you look like you fell from heaven.",
    "Are you a campfire? Because you're hot and I want to roast marshmallows.",
    "If you were a star, you'd be the brightest one in the sky.",
    "Your lips look lonely. Would they like to meet mine?",
    "Do you have a map? I just got lost in your eyes.",
    "If kisses were snowflakes, I'd send you a blizzard.",
    "You're the most beautiful person in this room. Do you know anyone else here?",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Is your name Google? Because you have everything I've been searching for.",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a name or can I call you mine?",
    "Is your smile made of magnets? Whenever I look at you, you attract me.",
    "I must be a snowflake because I've fallen for you.",
    "I'm not a photographer, but I can definitely picture us together.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "If you were a fruit, you'd be a fine-apple.",
    "I'm not a genie, but I can make your dreams come true.",
    "Is your name Honey? Because you're so sweet.",
    "You must be made of copper and tellurium because you're Cu-Te.",
    "Do you have a name or can I call you mine?",
    "Your smile could light up the darkest of rooms.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Do you have a map? I keep getting lost in your eyes.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a name or can I call you mine?",
    "Is your smile made of magnets? Whenever I look at you, you attract me.",
    "I must be a snowflake because I've fallen for you.",
    "I'm not a photographer, but I can definitely picture us together.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "If you were a fruit, you'd be a fine-apple.",
    "I'm not a genie, but I can make your dreams come true.",
    "Is your name Honey? Because you're so sweet.",
    "You must be made of copper and tellurium because you're Cu-Te.",
    "Do you have a name or can I call you mine?",
    "Your smile could light up the darkest of rooms.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "Are you a magician? Whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I've been searching for.",
    "Do you have a map? I keep getting lost in your eyes.",
    "If you were a vegetable, you'd be a cute-cumber!",
    "You must be a parking ticket because you've got 'Fine' written all over you.",
    "Do you have a name or can I call you mine?",
    "Is your smile made of magnets? Whenever I look at you, you attract me.",
    "I must be a snowflake because I've fallen for you.",
    "I'm not a photographer, but I can definitely picture us together.",
    "Are you a Wi-Fi signal? Because I'm feeling a connection.",
    "If you were a fruit, you'd be a fine-apple.",
    "I'm not a genie, but I can make your dreams come true.",
    "Is your name Honey? Because you're so sweet.",
    "You must be made of copper and tellurium because you're Cu-Te.",
    "Do you have a name or can I call you mine?",
    "Your smile could light up the darkest of rooms."
]

COMPLIMENT_LIST = [
    "You're really good!",
    "You're doing great!",
    "You're awesome!",
    "You're amazing!",
    "You're a star!",
    "You're a true talent!",
    "You're on fire!",
    "You're outstanding!",
    "You're exceptional!",
    "You're a rockstar!",
    "You're the best!",
    "You're a champion!",
    "You're a genius!",
    "You're a fantastic person!",
    "You make the world a better place!",
    "You're a source of inspiration!",
    "You're a ray of sunshine!",
    "You're incredibly talented!",
    "You're a role model!",
    "You're simply the greatest!",
    "You're a superstar!",
    "You're a shining example!",
    "You're phenomenal!",
    "You're a legend!",
    "You're a top-notch individual!",
]

##################### CMD LIST #########################
VALORANT_CMD = {
    'shoot': 'Shoots gun',
    'entry': 'Holds W for 10 seconds',
    'vc': 'Uses voice chat for 10 seconds',
    'crouch' : 'Holds Crouch for 5 seconds',
    'jump' : 'make me jump',
    'drop' : 'drop my gun',
    'ult' : 'Make me use my ult',
    'pistol' : 'Switch to my pistol',
    'knife' : 'Switch to my knife',
    'reload' : 'reloads my gun',
    'random_ability' : 'Use a random ability',
    'ability1' : 'using ability 1',
    'ability2' : 'using ability 2',
    'ability3' : 'using ability 3',
}

DEBUFF_CMD = {
    'america' : 'Hold down shoot button for 10 seconds',
    'slippery_hands' : 'Drop my weapon every 10 seconds 10 timess',
    'reload_paranoia' : 'make me reload a gun every 5 seconds 20 times'
}

AI_CMD = {
    'inspire' : 'it will inspire you',
    'bot_ai' : 'Jen Jen will say an inspirational quote',
    's' : 'This is Jen Jen\'s real voice',
    'compliment_me' : 'Are you feeling down UWU? Let me cheer you up',
    'degrade_me' : 'I\'ll degrade you',
    'bully_tritin' : 'self explanatory actually',
    'joke' : 'Says a dad joke cuz this bot is a daddy <3',
    'dice' : 'rolls a regular dice',
    'd20' : 'rolls a d20 dice'
}

SOUNDPAD_CMD = {
    'bot_snore' : 'snoreeeee',
    'bot_meow' : 'cat',
    "bot_raze" : 'fire in the whole'
}

help_message = f"**Valorant Commands:**\n"
for command, description in VALORANT_CMD.items():
    help_message += f"{command}: {description}\n"
help_message += f"=======================\n"
help_message += f"**Debuffs:**\n"
for command, description in DEBUFF_CMD.items():
    help_message += f"{command}: {description}\n"
help_message += f"=======================\n"
help_message += f"**Sentient AI:**\n"
for command, description in AI_CMD.items():
    help_message += f"{command}: {description}\n"
help_message += f"=======================\n"
help_message += f"**Soundpad:**\n"
for command, description in SOUNDPAD_CMD.items():
    help_message += f"{command}: {description}\n"
help_message += f"=======================\n"